import { createHash } from "node:crypto";
import { mkdir, readdir, readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { z } from "zod";
import {
  CLIENT_ADAPTERS,
  clientAdapterIdSchema,
} from "../src/client-adapter-specs";

const projectRoot = resolve(import.meta.dir, "..");
const evidenceDirectory = resolve(projectRoot, "evidence/client-evals");
const adapterEvidenceDirectory = resolve(projectRoot, "evidence/client-adapters");
export const GENERATED_CLIENT_COMPATIBILITY_PATH = resolve(
  projectRoot,
  "generated/client-compatibility.ts",
);
export const GENERATED_CLIENT_COMPATIBILITY_MARKDOWN_PATH = resolve(
  projectRoot,
  "docs/client-compatibility.md",
);

const qualificationEvidenceSchema = z.strictObject({
  schema: z.literal("asana-cli.client-eval-evidence.v1"),
  client: clientAdapterIdSchema,
  verdict: z.literal("passed"),
}).passthrough();

type Qualification = Readonly<
  | { kind: "generic-contract"; evidence: null; evidence_sha256: null }
  | { kind: "behavioral-eval"; evidence: string; evidence_sha256: string }
  | {
    kind: "adapter-only";
    evidence: string | null;
    evidence_sha256: string | null;
  }
>;

function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}

async function behavioralEvidence(): Promise<ReadonlyMap<string, Qualification>> {
  const evidence = new Map<string, Qualification>();
  const entries = await readdir(evidenceDirectory, { withFileTypes: true });
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
    const path = resolve(evidenceDirectory, entry.name);
    const content = await readFile(path, "utf8");
    const parsed = qualificationEvidenceSchema.parse(JSON.parse(content) as unknown);
    if (parsed.client === "generic-agent-skills") {
      throw new Error("Generic Agent Skills cannot be promoted by client behavioral evidence");
    }
    if (evidence.has(parsed.client)) {
      throw new Error(`Duplicate client behavioral evidence: ${parsed.client}`);
    }
    evidence.set(parsed.client, {
      kind: "behavioral-eval",
      evidence: `evidence/client-evals/${entry.name}`,
      evidence_sha256: sha256(content),
    });
  }
  return evidence;
}

async function adapterEvidence(): Promise<ReadonlyMap<string, Qualification>> {
  const evidence = new Map<string, Qualification>();
  const entries = await readdir(adapterEvidenceDirectory, { withFileTypes: true }).catch(
    (error: unknown) => {
      if (
        error && typeof error === "object" && "code" in error &&
        error.code === "ENOENT"
      ) return [];
      throw error;
    },
  );
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
    const path = resolve(adapterEvidenceDirectory, entry.name);
    const content = await readFile(path, "utf8");
    const parsed = z.strictObject({
      schema: z.literal("asana-cli.native-client-discovery.v1"),
      client: clientAdapterIdSchema,
      verdict: z.literal("passed"),
    }).passthrough().parse(JSON.parse(content) as unknown);
    evidence.set(parsed.client, {
      kind: "adapter-only",
      evidence: `evidence/client-adapters/${entry.name}`,
      evidence_sha256: sha256(content),
    });
  }
  return evidence;
}

export async function renderClientCompatibilityModule(): Promise<string> {
  const [evidence, nativeEvidence] = await Promise.all([
    behavioralEvidence(),
    adapterEvidence(),
  ]);
  const clients = Object.fromEntries(
    [...CLIENT_ADAPTERS]
      .sort((left, right) => left.id.localeCompare(right.id))
      .map((adapter) => {
        const qualification: Qualification = adapter.id === "generic-agent-skills"
          ? { kind: "generic-contract", evidence: null, evidence_sha256: null }
          : evidence.get(adapter.id) ?? nativeEvidence.get(adapter.id) ?? {
            kind: "adapter-only",
            evidence: null,
            evidence_sha256: null,
          };
        const support = qualification.kind === "generic-contract"
          ? "generic"
          : qualification.kind === "behavioral-eval"
            ? "supported"
            : "experimental";
        return [adapter.id, { support, qualification }];
      }),
  );
  const payload = JSON.stringify({
    schema: "asana-cli.client-compatibility.v1",
    clients,
  }, null, 2);
  return `// Generated by scripts/generate-client-compatibility.ts. DO NOT EDIT.\nexport const GENERATED_CLIENT_COMPATIBILITY = ${payload} as const;\n`;
}

export async function renderClientCompatibilityMarkdown(): Promise<string> {
  const [evidence, nativeEvidence] = await Promise.all([
    behavioralEvidence(),
    adapterEvidence(),
  ]);
  const rows = [...CLIENT_ADAPTERS]
    .sort((left, right) => left.id.localeCompare(right.id))
    .map((adapter) => {
      const qualification = adapter.id === "generic-agent-skills"
        ? "portable contract"
        : evidence.get(adapter.id)?.evidence ??
          nativeEvidence.get(adapter.id)?.evidence ??
          "adapter/lifecycle tests only";
      const support = adapter.id === "generic-agent-skills"
        ? "generic"
        : evidence.has(adapter.id)
          ? "supported"
          : "experimental";
      return `| \`${adapter.id}\` | \`${support}\` | \`${adapter.roots.user.join("/")}\` | \`${adapter.roots.project.join("/")}\` | ${qualification} |`;
    });
  return `# Client compatibility\n\n` +
    `> Generated by \`scripts/generate-client-compatibility.ts\`. Do not edit manually.\n\n` +
    `A client is \`supported\` only when a passed behavioral/security evidence record exists. ` +
    `A deterministic install adapter without that record remains \`experimental\`; the shared ` +
    `portable format remains \`generic\`.\n\n` +
    `| Client | Level | User root | Project root | Qualification |\n` +
    `| --- | --- | --- | --- | --- |\n${rows.join("\n")}\n`;
}

export async function generateClientCompatibility(
  options: Readonly<{ write?: boolean }> = {},
): Promise<string> {
  const output = await renderClientCompatibilityModule();
  if (options.write !== false) {
    await Promise.all([
      mkdir(dirname(GENERATED_CLIENT_COMPATIBILITY_PATH), { recursive: true }),
      mkdir(dirname(GENERATED_CLIENT_COMPATIBILITY_MARKDOWN_PATH), { recursive: true }),
    ]);
    const current = Bun.file(GENERATED_CLIENT_COMPATIBILITY_PATH);
    if (!(await current.exists()) || await current.text() !== output) {
      await Bun.write(GENERATED_CLIENT_COMPATIBILITY_PATH, output);
    }
    const markdown = await renderClientCompatibilityMarkdown();
    const currentMarkdown = Bun.file(GENERATED_CLIENT_COMPATIBILITY_MARKDOWN_PATH);
    if (!(await currentMarkdown.exists()) || await currentMarkdown.text() !== markdown) {
      await Bun.write(GENERATED_CLIENT_COMPATIBILITY_MARKDOWN_PATH, markdown);
    }
  }
  return output;
}

if (import.meta.main) {
  await generateClientCompatibility();
  process.stdout.write("Generated generated/client-compatibility.ts\n");
}
